version: '3'
services:

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - hex-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        container_name: app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app:rw
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - hex-network
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: redis-test
        networks:
            - hex-network

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass password
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            - hex-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq
        networks:
            - hex-network
networks:
    hex-network:
        driver: bridge
